### ISSUE TITLE
PHP 7 compatibility broken

### ISSUE THREAD

**Issue by khromov** [appserver-io/webserver#202]
Running  `composer update`:

```bash
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - crunch/fastcgi 2.x-dev requires php ~5.4 -> your PHP version (7.0.22) does not satisfy that requirement.
    - appserver-io/webserver dev-master requires crunch/fastcgi 2.x-dev -> satisfiable by crunch/fastcgi[2.x-dev].
    - Installation request for appserver-io/webserver dev-master -> satisfiable by appserver-io/webserver[dev-master].
```

**Comment by wagnert** [comment]
Hi, you can try it with `./composer.phar install --ignore-platform-reqs` that should work. But we've never tried it with PHP 7.0.x but only with PHP 7.2.x and the latests pthreads dev-master installed.

**Comment by wagnert** [comment]
Hi @khromov , i've update our docker container https://hub.docker.com/r/appserver/webserver/builds/ and added a new tag `appserver/webser:php7-2` with a running PHP 7.2 webserver.
